version: '2'
services:
    app:
        build: app
    app1:
        build: app1
    volumes:
      - /home/ruslan/nginx:/usr/share/nginx/html
    proxy:
        build: proxy
        ports:
        - "80:80"



    
