version: '3'
services:
    app:
        build: app
    app1:
        build: app1
    proxy:
        build: proxy
        ports:
        - "80:80"
    volumes:
      - /home/ruslan/nginx:/usr/share/nginx/html



    
